version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beti-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_NAME=Beti Backend
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8091
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=beti_db
      - DB_USERNAME=beti_user
      - DB_PASSWORD=beti_password
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    depends_on:
      - db
    ports:
      - "8070:80"
    networks:
      - beti-network

  db:
    image: mariadb:10.6
    container_name: beti-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: beti_db
      MYSQL_USER: beti_user
      MYSQL_PASSWORD: beti_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - beti_mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8079:3306"
    networks:
      - beti-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: beti-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8071:80"
    depends_on:
      - db
    networks:
      - beti-network

volumes:
  beti_mysql_data:
    driver: local

networks:
  beti-network:
    driver: bridge 